documentation:
  operating_system: Ubuntu 18.04
  python_version: 3.8.10
  zeek_version: 4.2.1
  argus_version: 3.0.8.2
  ra_client_version: 3.0.8 
  expected_outputs: 
    - unsw_nb15_dataset.csv

setup_options:
  current_directory: ENV_PWD
  working_directory: ENV_PWD/unsw_nb15_dataset

step_acquire_source_data:
  - python src/step_acquire_source_data/downloader.py ${setup_options.working_directory}

step_feature_processing:
  packet_level:
    - rm -f ${setup_options.working_directory}/17-2-2015_1.argus
    - argus -S 60 -m -r ${setup_options.working_directory}/17-2-2015_1.pcap -w ${setup_options.working_directory}/17-2-2015_1.argus
    - ./src/argus/ra_wrapper.bash ${setup_options.working_directory} 17-2-2015_1.argus argus_features.csv ./src/step_feature_processing/packet_level/__load__.argus

  flow_level:
    - ./src/zeek/zeek-wrapper.bash ${setup_options.current_directory}/src/zeek/packages ${setup_options.working_directory} mlfeatures -r ${setup_options.working_directory}/17-2-2015_1.pcap

  network_level:
    - ./src/python/python-wrapper.bash ${setup_options.working_directory} ${setup_options.current_directory}/src/step_feature_processing/network_level ${setup_options.working_directory}/features.log

step_label_processing:
  packet_level:

  flow_level:
    - ./src/python/python-wrapper.bash ${setup_options.working_directory} ${setup_options.current_directory}/src/step_label_processing/flow_level /dev/null

  network_level:

step_final_dataset_processing:
  - python ./src/step_post_processing/combine_features.py ${setup_options.working_directory} unsw_nb15_dataset.csv
